name: uxf
description: A Command line tool to download packages from https://uxflutter.com
version: 1.1.2
# repository: https://github.com/my_org/my_repo
homepage: https://uxflutter.com

environment:
  sdk: ^3.5.3

executables:
  uxf: 

# Add regular dependencies here.
dependencies:
  archive: ^3.6.1
  args: ^2.6.0
  http: ^1.2.2
  path: ^1.9.0
  tiny_storage: ^1.1.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
